monolog:
    channels: ['import', 'export']
    handlers:
        import:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/import.log'
            channels: import
        export:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/export.log'
            channels: export
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        error:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-error.log"
            level: error
        console:
            type: console
            level: debug
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
